### PR TITLE
Feature/consul support

### PR DESCRIPTION
**Pull request by nii236**
This pull request adds [consul](https://www.consul.io/) support by implementing the cacher interface.

### CODE REVIEW

**Comment by glinton** [comment]
If you get consul added to the [travis tests](https://github.com/nanopack/shaman/blob/master/.travis.yml) so they pass, I'll merge this one time. Thanks for the great contribution!

**Comment by tylerflint** [comment]
This is looking great! Fantastic work.

**Comment by nii236** [comment]
Travis is finally passing now!

**Comment by glinton** [comment]
Thanks!

**Pull request merged**
